name: Bug report
description: Report a reproducible problem in Forkline
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps to reproduce the issue.
      placeholder: |
        1. Open...
        2. Click...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 14.x / Ubuntu 24.04 / Windows 11
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node version
      placeholder: node -v
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and screenshots
      description: Paste relevant logs or attach screenshots.

