name: Feature request
description: Propose an improvement for Forkline
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user problem are you trying to solve?
      placeholder: Describe the pain point clearly.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should Forkline do?
      placeholder: Describe the behavior, workflow, and expected outcome.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other options you evaluated.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Mockups, references, edge cases, etc.

